name: listen_it
description: Reactive primitives for Flutter - observable collections and powerful operators. Work with ValueNotifiers like Streams. Includes ListNotifier, MapNotifier, SetNotifier. Previously published as functional_listener.
version: 5.2.0
homepage: https://github.com/flutter-it/listen_it

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  collection: ^1.17.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  leak_tracker:
  lint:
  watch_it:
    path: ../watch_it
